service: portfolio-backend
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:179540755677:table/PortfolioTable

functions:
  health:
    handler: src/handlers/healthHandler.health
    events:
      - httpApi:
          path: /ping
          method: get
  createPortfolio:
    handler: src/handlers/portfolioHandler.createPortfolio
    events:
      - httpApi:
          path: /portfolio
          method: post
  getPortfolios:
    handler: src/handlers/portfolioHandler.getPortfolios
    events:
      - httpApi:
          path: /portfolios
          method: get
  getPortfolio:
    handler: src/handlers/portfolioHandler.getPortfolio
    events:
      - httpApi:
          path: /portfolio/{id}
          method: get
  updatePortfolio:
    handler: src/handlers/portfolioHandler.updatePortfolio
    events:
      - httpApi:
          path: /portfolio/{id}
          method: patch

resources:
  Resources:
    PortfolioTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PortfolioTable
        BillingMode: 'PAY_PER_REQUEST'
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
